### ISSUE TITLE
integrating with vimwiki

### ISSUE THREAD

**Issue by nathanbraun** [phb1/gtd.vim#1]
Is this something that would work with vimwiki?

**Comment by ghost** [comment]
Hello,

No it is not. Gtd.vim works with a note directory and deals itself with filenames. It uses a syntax to search notes into the directory regarding your request.

**Comment by tfabbri** [comment]
Have you planned any sort of integration with vimwiki?

**Comment by ghost** [comment]
No, I haven't.
