### ISSUE TITLE
E154 duplicate tag "gtd-completion" in file doc\gtd.txt

### ISSUE THREAD

**Issue by rhoellwarthwork** [phb1/gtd.vim#5]
Hello,

my vim version is 8.1.20, MS-Win 32 Bit Huge Version with Gui and OLE.  

When I issue :helptag ....\gtd.vim\doc\ I get the above error.
I edited the file and changed the tag to gtd-completion2.
After that the :helptag command did work correct.

greetings
ronald

**Comment by ghost** [comment]
Thank you Ronald
