### ISSUE TITLE
Remove default context or action

### ISSUE THREAD

**Issue by folofjc** [phb1/gtd.vim#8]
Searches with `:Gtd` apply the default context (as does `:GtdReview` as far as I can tell). I cannot see an easy way to see all contexts without running something like `"let g:gtd#default_context = ''`. Should be able to easily remove a default context or action from searches.

Easiest would be to allow `:GtdContext` and `:GtdAction` to take no argument.

**Comment by fifi2** [comment]
You can use `:Gtd!` syntax to force the exact search you like without any context addition. The same behavior applies on `:GtdReview!`.

Is is enough this way?
