### ISSUE TITLE
Show context/action/hashtag in search result

### ISSUE THREAD

**Issue by folofjc** [phb1/gtd.vim#9]
For any searches where the context/action/hashtag is NOT part of the search, should show it on the line with the filename. So if the search is for `:Gtd !inbox` with no default context, then the context (and any hashtags) should be on each line of the result (after the title).

**Comment by fifi2** [comment]
This request is not simple to implement and I'm not sure it will be interesting for everyone. You have to keep in mind that searches might be complex (you gave the example "!inbox" but it also can be "(!inbox + !todo) @work Y2021 M04").

Plus I'm not sure to understand the use case in a GTD process where you can have such a need. If you really need it, feel free to explain me much about this.

**Comment by folofjc** [comment]
Sorry, I wasn't able to use this extension in a way that helped my GTD, so I am now using something else. I'll close my issues.

**Comment by fifi2** [comment]
Hi,

I'm sorry to read that. Feel free to give me a feedback regarding what you were not able to do with Gtd.vim.

Have a nice GTD elsewhere ;)
